# Generated by Django 5.0.2 on 2024-03-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default name', max_length=50)),
                ('desc', models.TextField(default='default description')),
                ('img', models.ImageField(default=' default img.jpg', upload_to='pics')),
                ('price', models.FloatField(default=0.0)),
                ('sub', models.TextField(default='default subject')),
            ],
        ),
    ]
